// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SysMatEigen
SEXP SysMatEigen(SEXP Min);
RcppExport SEXP _CELINA_SysMatEigen(SEXP MinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Min(MinSEXP);
    rcpp_result_gen = Rcpp::wrap(SysMatEigen(Min));
    return rcpp_result_gen;
END_RCPP
}
// LmmAICovarites
SEXP LmmAICovarites(SEXP Yin, SEXP Xin, SEXP Win, SEXP numVarin, SEXP tauin, SEXP fixtauin, SEXP tolin);
RcppExport SEXP _CELINA_LmmAICovarites(SEXP YinSEXP, SEXP XinSEXP, SEXP WinSEXP, SEXP numVarinSEXP, SEXP tauinSEXP, SEXP fixtauinSEXP, SEXP tolinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Yin(YinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type Win(WinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type numVarin(numVarinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type fixtauin(fixtauinSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tolin(tolinSEXP);
    rcpp_result_gen = Rcpp::wrap(LmmAICovarites(Yin, Xin, Win, numVarin, tauin, fixtauin, tolin));
    return rcpp_result_gen;
END_RCPP
}
// TestStatfast
List TestStatfast(arma::vec yin, arma::vec Pyin, arma::mat Win, arma::vec Xin, arma::mat& XKXin, arma::vec tauin, arma::mat& Prightin);
RcppExport SEXP _CELINA_TestStatfast(SEXP yinSEXP, SEXP PyinSEXP, SEXP WinSEXP, SEXP XinSEXP, SEXP XKXinSEXP, SEXP tauinSEXP, SEXP PrightinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type yin(yinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Pyin(PyinSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Win(WinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Xin(XinSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type XKXin(XKXinSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type tauin(tauinSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type Prightin(PrightinSEXP);
    rcpp_result_gen = Rcpp::wrap(TestStatfast(yin, Pyin, Win, Xin, XKXin, tauin, Prightin));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CELINA_SysMatEigen", (DL_FUNC) &_CELINA_SysMatEigen, 1},
    {"_CELINA_LmmAICovarites", (DL_FUNC) &_CELINA_LmmAICovarites, 7},
    {"_CELINA_TestStatfast", (DL_FUNC) &_CELINA_TestStatfast, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_CELINA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
