# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SysMatEigen <- function(Min) {
    .Call(`_CELINA_SysMatEigen`, Min)
}

LmmAICovarites <- function(Yin, Xin, Win, numVarin, tauin, fixtauin, tolin) {
    .Call(`_CELINA_LmmAICovarites`, Yin, Xin, Win, numVarin, tauin, fixtauin, tolin)
}

TestStatfast <- function(yin, Pyin, Win, Xin, XKXin, tauin, Prightin) {
    .Call(`_CELINA_TestStatfast`, yin, Pyin, Win, Xin, XKXin, tauin, Prightin)
}

